# Generated by Django 2.2 on 2019-05-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maked', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('barcode', models.BigIntegerField(blank=True, null=True, verbose_name='Трек-номер')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
